spring.application.name=camel
server.port=8082

# API login

gympr.admin.username=admin
gympr.admin.password=admin123

# ActiveMQ url
spring.activemq.broker-url=tcp://localhost:61616
camel.component.activemq.broker-url=tcp://localhost:61616

# Payload AES encryption key (16 characters for AES-128)
# Voluntary not safe
gympr.payload.encryption-key=MySuperSecretKey

# API Endpoints
gympr.api.login-url=http://localhost:8081/api/auth/login
gympr.api.refresh-url=http://localhost:8081/api/auth/refresh
gympr.api.base-url=http://localhost:8081/api/lifts

# App Configuration
gympr.output.dir=output/responses
gympr.timestamp.format=yyyyMMdd-HHmmss
gympr.entity.name=record


